# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the sasquatch branch
  push:
    branches:
      - master
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        architecture:
          - amd64
          - arm64
          - arm/v7
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build Debian package
        uses: dawidd6/action-debian-package@v1.5.0
        with:
          os_distribution: bookworm
          cpu_architecture: ${{ matrix.architecture }}
      - name: Upload DEB artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}/*.deb
